name: IPv6 Detection

on:
  push:
    branches:
      - main

jobs:
  ipv6-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect IPv6
        run: |
          IPV6_ADDRESS="http://[2409:8087:1:20:20::2c]/otttv.bj.chinamobile.com/PLTV/88888888/224/3221226895/1.m3u8?GuardEncType=2&accountinfo=%7E%7EV2.0%7EI0Rkc6neBYgfpoJ1yud8Fw%7E_eNUbgU9sJGUcVVduOMKhafLvQUgE_zlz_7pvDimJNPpqgHe3PQ5GNQoO-yUgA8C%2CEND"  # 替换为你要检测的IPv6地址
          if ping6 -c 3 $IPV6_ADDRESS > /dev/null 2>&1; then
            echo "IPv6 address $IPV6_ADDRESS is reachable."
          else
            echo "IPv6 address $IPV6_ADDRESS is unreachable."
          fi