name: Run FFmpeg Stream Test

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行（北京时间8点）

jobs:
  run-ffmpeg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Run FFmpeg Script
      run: |
        python main.py

    - name: Upload Log File
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg-logs
        path: ffmpeg_log_*.log